### ISSUE TITLE
Google Map Not Showing in Chrome

### ISSUE THREAD

**Issue by pleasantgears** [noxidsoft/mod_gmdirections#1]
Hi, The map is not showing in Chrome desktop. Very weird. When I switch the user agent to Android, the map showed up. It is also showing in Android chrome in phone or tablet BUT when "Request Desktop Site" is turned on, the map does not load.

Thank you for any support that you can provide.

**Comment by pleasantgears** [comment]
Nevermind. This is caused by conflict with Greybox javascript. Thanks.

**Comment by noxidsoft** [comment]
I'd be interested to know if you got it to work? If you have a screenshot/error message, are you able to pass it on and I'll add it to testing down the track.

**Comment by pleasantgears** [comment]
Yes, I got it to work. It turned out that the google map is conflicting with my lightbox script called Greybox. Whenever there is a call to greybox files, the map won't load. Might be something to do with iframe.

Thank you for your reply.



-----Original Message-----
